CREATE TABLE department(
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_type VARCHAR2(40) NOT NULL UNIQUE, 
    department_location VARCHAR2(30) DEFAULT 'N/A' NOT NULL, 
    department_description VARCHAR2(100)
); 

CREATE TABLE room(
    room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    facility_type VARCHAR2(50) NOT NULL,
    floor_num INT NOT NULL, 
    equipment VARCHAR2(200), 
    availability CHAR(1) DEFAULT 'Y' NOT NULL CHECK (availability IN ('Y', 'N')), 
    max_occupancy INT NOT NULL
); 

CREATE TABLE employee(
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    first_name VARCHAR2(25) NOT NULL, 
    last_name VARCHAR2(25) NOT NULL, 
    department_id INT REFERENCES department(department_id), 
    phone_number VARCHAR2(25) UNIQUE, 
    email VARCHAR2(100) NOT NULL UNIQUE, 
    employment_type VARCHAR2(25) DEFAULT 'full-time' NOT NULL, 
    manager_id INT REFERENCES employee(employee_id)
); 

CREATE TABLE doctor(
    doctor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    employee_id INT REFERENCES employee(employee_id), 
    medical_license_number VARCHAR2(25) UNIQUE NOT NULL, 
    speciality_field VARCHAR2(50) NOT NULL, 
    office_number INT REFERENCES room(room_id) 
); 

CREATE TABLE patient(
    patient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    first_name VARCHAR2(25) NOT NULL,
    last_name VARCHAR2(25) NOT NULL,
    patient_status VARCHAR2(25) DEFAULT 'Stable' NOT NULL, 
    diagnosis VARCHAR2(50) NOT NULL,
    room_id INT REFERENCES room(room_id), 
    phone_number VARCHAR2(25) UNIQUE
); 
 

CREATE TABLE medication(
    medication_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    generic_name VARCHAR2(50) NOT NULL UNIQUE, 
    prescription_required CHAR(1) DEFAULT 'Y' NOT NULL CHECK (prescription_required IN ('Y', 'N')), 
    stock INT NOT NULL 
); 

CREATE TABLE prescription(
    prescription_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
    patient_id INT REFERENCES patient(patient_id), 
    medication_id INT REFERENCES medication(medication_id), 
    doctor_id INT REFERENCES doctor(doctor_id), 
    dosage VARCHAR2(25) NOT NULL,
    frequency VARCHAR2(25) NOT NULL
); 

CREATE TABLE patient_admission(
    doctor_id INT REFERENCES doctor(doctor_id), 
    patient_id INT REFERENCES patient(patient_id), 
    room_id INT REFERENCES room(room_id), 
    date_admitted DATE DEFAULT SYSDATE NOT NULL, 
    date_out DATE, 
    CONSTRAINT pk_patient_admission PRIMARY KEY(patient_id, date_admitted) 
);

CREATE TABLE staff_scheduling(
    employee_id INT REFERENCES employee(employee_id), 
    shift_type VARCHAR2(25) NOT NULL,
    time_in DATE DEFAULT SYSDATE NOT NULL,
    time_out DATE,
    break_time INT DEFAULT 60, 
    work_status VARCHAR2(25) DEFAULT 'regular hours',
    CONSTRAINT pk_staff_scheduling PRIMARY KEY(employee_id, time_in) 
); 


